GlobalDigitalLibraryio/book-api

build.sh
GlobalDigitalLibraryio/issues#64
=> #64: Fail fast if any intermediate steps fail

src/main/scala/no/gdl/bookapi/BookApiProperties.scala, src/main/scala/no/gdl/bookapi/service/ConverterService.scala, src/test/scala/no/gdl/bookapi/service/ConverterServiceTest.scala
GlobalDigitalLibraryio/issues#85
=> #85: Use CloudFront URLs for downloads

src/main/scala/no/gdl/bookapi/BookApiProperties.scala
GlobalDigitalLibraryio/issues#10
=> #10: Use CloudFront URL in staging

src/main/scala/no/gdl/bookapi/BookApiProperties.scala
GlobalDigitalLibraryio/issues#10
=> #10: CloudFront URL in prod

src/main/scala/no/gdl/bookapi/service/WriteService.scala
=> #62: Use license id, not publisher id

src/main/scala/no/gdl/bookapi/controller/OPDSController.scala, src/test/scala/no/gdl/bookapi/controller/OPDSControllerTest.scala
GlobalDigitalLibraryio/issues#113
=> #113: Added publisher in metadata in opds-feed

src/main/scala/no/gdl/bookapi/controller/OPDSController.scala, src/test/scala/no/gdl/bookapi/controller/OPDSControllerTest.scala
GlobalDigitalLibraryio/issues#113
=> #113: Added createddate, publisheddate and license to opds-feed

src/main/scala/no/gdl/bookapi/BookApiProperties.scala
GlobalDigitalLibraryio/issues#121 Replaced cloudfront url with custom url.
=> #121 Replaced cloudfront urls with custum urls.

project/build.properties
GlobalDigitalLibraryio/issues#124 Bumping version from 0.13.13 to 0.15.16
=> #124 bumping sbt version

src/main/scala/no/gdl/bookapi/BookApiProperties.scala, src/main/scala/no/gdl/bookapi/BookSwagger.scala, src/main/scala/no/gdl/bookapi/controller/BooksController.scala, src/main/scala/no/gdl/bookapi/controller/EditorsPickController.scala
GlobalDigitalLibrary/issues#111
* Removed all auth from book-api since is not needed.
* Prepare to use Auth0 later if needed after all.
=> #111 Token based authentication from Auth0

src/main/scala/no/gdl/bookapi/BookApiProperties.scala, src/main/scala/no/gdl/bookapi/service/ConverterService.scala, src/main/scala/no/gdl/bookapi/service/FeedService.scala, src/test/scala/no/gdl/bookapi/service/FeedServiceTest.scala
GlobalDigitalLibraryio/issues#127 
Changed feeds to use cloudfront urls internally.
=> #127 Add cloudfront url to opds feeds

build.sbt, src/main/scala/no/gdl/bookapi/BookSwagger.scala, src/main/scala/no/gdl/bookapi/controller/BooksController.scala, src/main/scala/no/gdl/bookapi/controller/GdlController.scala, src/main/scala/no/gdl/bookapi/controller/LanguageController.scala, src/main/scala/no/gdl/bookapi/model/api/Book.scala, src/main/scala/no/gdl/bookapi/service/ConverterService.scala, src/test/scala/no/gdl/bookapi/TestData.scala, src/test/scala/no/gdl/bookapi/controller/BooksControllerTest.scala
GlobalDigitalLibraryio/issues#134
=> #134: Added endpoints for my books

build.sbt, src/main/scala/ScalatraBootstrap.scala, src/main/scala/no/gdl/bookapi/BookApiProperties.scala, src/main/scala/no/gdl/bookapi/ComponentRegistry.scala, src/main/scala/no/gdl/bookapi/controller/TranslationsController.scala, src/main/scala/no/gdl/bookapi/integration/crowdin/CrowdinClient.scala, src/main/scala/no/gdl/bookapi/integration/crowdin/CrowdinClientBuilder.scala, src/main/scala/no/gdl/bookapi/model/crowdin/SupportedLanguage.scala, src/main/scala/no/gdl/bookapi/service/translation/SupportedLanguageService.scala, src/test/scala/no/gdl/bookapi/TestEnvironment.scala, src/test/scala/no/gdl/bookapi/controller/TranslationsControllerTest.scala, src/test/scala/no/gdl/bookapi/service/translation/SupportedLanguageServiceTest.scala
This is just a move of the supported-languages from translation-api to book-api
=> Issue#158 Move supported-languages to book-api

build.sbt
GlobalDigitalLibraryio/issues#161
=> #161: Bumped version of network

src/main/scala/no/gdl/bookapi/ComponentRegistry.scala, src/main/scala/no/gdl/bookapi/controller/TranslationsController.scala, src/main/scala/no/gdl/bookapi/model/api/Book.scala, src/main/scala/no/gdl/bookapi/service/translation/TranslationService.scala, src/test/scala/no/gdl/bookapi/TestEnvironment.scala
Based on https://github.com/GlobalDigitalLibraryio/book-api/pull/31 so must be merged afterwards.
=> Issue#158 add endpoint for post translation

build.sbt
GlobalDigitalLibraryio/issues#176
=> #176: Use language-lib without macrolanguage-comments

src/main/scala/no/gdl/bookapi/BookApiProperties.scala, src/main/scala/no/gdl/bookapi/integration/ImageApiClient.scala, src/main/scala/no/gdl/bookapi/service/ContentConverter.scala, src/test/scala/no/gdl/bookapi/service/ContentConverterTest.scala
GlobalDigitalLibraryio/issues#187
* Always return None if exeption.
Note: Wrong issue id in commit.
=> #168 Do not throw exception if image-api fails

src/main/scala/no/gdl/bookapi/integration/ElasticClient.scala
GlobalDigitalLibraryio/issues#168
* Fix signing of searches
=> #168 Use NDLA way of signing

src/main/scala/no/gdl/bookapi/repository/TranslationRepository.scala, src/main/scala/no/gdl/bookapi/service/search/IndexBuilderService.scala, src/main/scala/no/gdl/bookapi/service/search/IndexService.scala, src/main/scala/no/gdl/bookapi/service/search/SearchService.scala
GlobalDigitalLibraryio/issues#168
* Only reindex requested index if index not existing.
* Full reindex happens at import and via gdl index build env book-api
=> #168 Only index requested index when error.

src/main/resources/feedLocalization/amh.properties, src/main/resources/feedLocalization/eng.properties, src/main/resources/feedLocalization/nob.properties, src/test/scala/no/gdl/bookapi/service/FeedLocalizationServiceTest.scala
GlobalDigitalLibraryio/issues#94
=> Issue#94 fix title in nav feeds

src/main/scala/no/gdl/bookapi/service/FeedService.scala, src/test/scala/no/gdl/bookapi/service/FeedServiceTest.scala
GlobalDigitalLibraryio/issues#223
=> #223: Use local displayname if it exists

src/main/scala/no/gdl/bookapi/service/search/IndexService.scala
GlobalDigitalLibraryio/issues#230
* Setting boost for title to 2.
=> #230 Add boost to title

src/main/scala/no/gdl/bookapi/controller/SearchController.scala, src/main/scala/no/gdl/bookapi/model/Language.scala, src/main/scala/no/gdl/bookapi/model/domain/Sort.scala, src/main/scala/no/gdl/bookapi/service/FeedService.scala, src/main/scala/no/gdl/bookapi/service/search/IndexService.scala, src/main/scala/no/gdl/bookapi/service/search/SearchService.scala, src/test/scala/no/gdl/bookapi/controller/SearchControllerTest.scala, src/test/scala/no/gdl/bookapi/service/search/SearchServiceIntegrationTest.scala
GlobalDigitalLibrary/issues#230
* Removed sorting when searching with query
=> #230 Fixed sorting at search

src/main/scala/no/gdl/bookapi/model/api/Book.scala, src/test/scala/no/gdl/bookapi/TestData.scala, src/test/scala/no/gdl/bookapi/service/search/SearchServiceIntegrationTest.scala
GlobalDigitalLibraryio/issues#231
* Added forgotten languate
=> #231 Add language to book-hit

src/main/scala/no/gdl/bookapi/controller/BooksController.scala, src/main/scala/no/gdl/bookapi/controller/SearchController.scala, src/main/scala/no/gdl/bookapi/model/api/Book.scala, src/main/scala/no/gdl/bookapi/service/ConverterService.scala, src/main/scala/no/gdl/bookapi/service/FeedService.scala, src/main/scala/no/gdl/bookapi/service/ReadService.scala, src/main/scala/no/gdl/bookapi/service/search/IndexService.scala, src/main/scala/no/gdl/bookapi/service/search/SearchService.scala, src/test/scala/no/gdl/bookapi/controller/BooksControllerTest.scala, src/test/scala/no/gdl/bookapi/controller/SearchControllerTest.scala, src/test/scala/no/gdl/bookapi/service/FeedServiceTest.scala, src/test/scala/no/gdl/bookapi/service/ReadServiceTest.scala, src/test/scala/no/gdl/bookapi/service/search/IndexServiceTest.scala, src/test/scala/no/gdl/bookapi/service/search/SearchServiceIntegrationTest.scala
GlobalDigitalLibraryio/issues#236
* Rewrote book search to only return bookhit.
* Swaggerdoc works again.
=> #236 Search result can only be bookhit

src/main/scala/no/gdl/bookapi/model/api/Book.scala, src/main/scala/no/gdl/bookapi/service/ConverterService.scala, src/main/scala/no/gdl/bookapi/service/search/IndexService.scala, src/main/scala/no/gdl/bookapi/service/search/SearchService.scala, src/test/scala/no/gdl/bookapi/TestData.scala, src/test/scala/no/gdl/bookapi/service/search/SearchServiceIntegrationTest.scala
GlobalDigitalLibraryio/issues#240
* Fixed sort on title
* Added dateAdded for sort.
=> #240 Fix sorting on title

build.sbt
=> #62: Bump language lib

src/main/scala/no/gdl/bookapi/repository/TranslationRepository.scala
GlobalDigitalLibraryio/issues#220
=> #220: Missing comma

src/main/scala/no/gdl/bookapi/repository/TranslationRepository.scala, src/main/scala/no/gdl/bookapi/service/WriteService.scala, src/main/scala/no/gdl/bookapi/service/translation/TranslationService.scala, src/test/scala/no/gdl/bookapi/service/translation/TranslationServiceTest.scala
GlobalDigitalLibraryio/issues#220
* Rewrite from sql interpolating string.
=> #220 rewrite sql to avoid formatting problems.

build.sbt
GlobalDigitalLibraryio/issues#256
* Remove old deprecated docker image.
=> #256 New docker image

src/main/resources/db/migration/V21__Add_source_to_book.sql, src/main/scala/no/gdl/bookapi/model/api/Book.scala, src/main/scala/no/gdl/bookapi/model/api/internal/Internal.scala, src/main/scala/no/gdl/bookapi/model/domain/Book.scala, src/main/scala/no/gdl/bookapi/repository/BookRepository.scala, src/main/scala/no/gdl/bookapi/service/ConverterService.scala, src/main/scala/no/gdl/bookapi/service/WriteService.scala, src/test/scala/no/gdl/bookapi/TestData.scala, src/test/scala/no/gdl/bookapi/repository/BookRepositoryTest.scala, src/test/scala/no/gdl/bookapi/repository/RepositoryTestHelpers.scala
GlobalDigitalLibraryio/issues#260
=> #260: Added source to book

src/main/scala/io/digitallibrary/bookapi/controller/CategoriesController.scala, src/main/scala/io/digitallibrary/bookapi/service/ReadService.scala, src/test/scala/io/digitallibrary/bookapi/controller/CategoriesControllerTest.scala, src/test/scala/io/digitallibrary/bookapi/service/ReadServiceTest.scala
=> #221: Avoid duplicate reading levels

src/main/scala/io/digitallibrary/bookapi/controller/BooksController.scala, src/main/scala/io/digitallibrary/bookapi/controller/CategoriesController.scala, src/main/scala/io/digitallibrary/bookapi/model/api/Book.scala, src/main/scala/io/digitallibrary/bookapi/repository/TranslationRepository.scala, src/main/scala/io/digitallibrary/bookapi/service/ConverterService.scala, src/main/scala/io/digitallibrary/bookapi/service/FeedService.scala, src/main/scala/io/digitallibrary/bookapi/service/ReadService.scala, src/main/scala/io/digitallibrary/bookapi/service/search/SearchService.scala, src/test/scala/io/digitallibrary/bookapi/controller/BooksControllerTest.scala, src/test/scala/io/digitallibrary/bookapi/controller/CategoriesControllerTest.scala, src/test/scala/io/digitallibrary/bookapi/repository/TranslationRepositoryTest.scala, src/test/scala/io/digitallibrary/bookapi/service/ReadServiceTest.scala, src/test/scala/io/digitallibrary/bookapi/service/search/SearchServiceIntegrationTest.scala
GlobalDigitalLibraryio/issues#266
=> Issue#266 add categories facet to opds feeds

src/main/scala/io/digitallibrary/bookapi/model/api/Book.scala, src/main/scala/io/digitallibrary/bookapi/service/ConverterService.scala, src/test/scala/io/digitallibrary/bookapi/TestData.scala
GlobalDigitalLibraryio/issues#253
=> #253: Exposing chapterType in api

src/main/resources/feedLocalization/amh.properties, src/main/resources/feedLocalization/eng.properties, src/main/resources/feedLocalization/nob.properties, src/main/scala/io/digitallibrary/bookapi/BookApiProperties.scala, src/main/scala/io/digitallibrary/bookapi/controller/OPDSController.scala, src/main/scala/io/digitallibrary/bookapi/service/FeedLocalizationService.scala, src/main/scala/io/digitallibrary/bookapi/service/FeedService.scala, src/test/scala/io/digitallibrary/bookapi/controller/OPDSControllerTest.scala, src/test/scala/io/digitallibrary/bookapi/service/FeedLocalizationServiceTest.scala, src/test/scala/io/digitallibrary/bookapi/service/FeedServiceTest.scala
=> Issue#221 use categories in opds feeds

src/main/resources/db/migration/V23__Update_reading_levels.sql
=> #221: Reading level 5 -> 'read-aloud'

src/main/scala/io/digitallibrary/bookapi/service/WriteService.scala
GlobalDigitalLibraryio/issues#273
* Index single book at import.
=> #273 Index single book at import.

src/main/scala/io/digitallibrary/bookapi/service/FeedService.scala
=> #221: Use translated category title

src/main/scala/io/digitallibrary/bookapi/service/FeedService.scala, src/test/scala/io/digitallibrary/bookapi/service/FeedServiceTest.scala
=> #221: Correct root of reqding levels

src/main/scala/io/digitallibrary/bookapi/integration/crowdin/CrowdinClient.scala
GlobalDigitalLibraryio/issues#277
=> #277: Substituting invalid characters when transfering to crowdin

src/main/resources/db/migration/V25__Add_licenses.sql
=> #62: Add more licenses

src/main/scala/io/digitallibrary/bookapi/controller/BooksController.scala, src/main/scala/io/digitallibrary/bookapi/controller/SearchController.scala
Fixes GlobalDigitalLibraryio/issues#271
* Added sort in docs.
=> #271 add sort in docs

src/main/scala/io/digitallibrary/bookapi/service/search/SearchService.scala, src/test/scala/io/digitallibrary/bookapi/TestData.scala, src/test/scala/io/digitallibrary/bookapi/service/search/SearchServiceIntegrationTest.scala
GlobalDigitalLibraryio/issues#285
=> #285: Similar now filters on category

src/main/scala/io/digitallibrary/bookapi/controller/OPDSController.scala, src/main/scala/io/digitallibrary/bookapi/model/api/Book.scala, src/main/scala/io/digitallibrary/bookapi/service/FeedService.scala
GlobalDigitalLibraryio/issues#276
=> #276: Lookup localized level text

src/main/resources/feedLocalization/am.properties, src/main/resources/feedLocalization/en.properties, src/main/resources/feedLocalization/nb.properties, src/main/scala/io/digitallibrary/bookapi/BookApiProperties.scala, src/main/scala/io/digitallibrary/bookapi/controller/OPDSController.scala, src/main/scala/io/digitallibrary/bookapi/service/FeedLocalizationService.scala, src/main/scala/io/digitallibrary/bookapi/service/FeedService.scala, src/test/scala/io/digitallibrary/bookapi/controller/OPDSControllerTest.scala, src/test/scala/io/digitallibrary/bookapi/service/FeedLocalizationServiceTest.scala, src/test/scala/io/digitallibrary/bookapi/service/FeedServiceTest.scala
GlobalDigitalLibraryio/issues#200
=> #200: Remove nav.xml from OPDS feeds

src/main/scala/io/digitallibrary/bookapi/BookApiProperties.scala, src/test/scala/io/digitallibrary/bookapi/controller/FeaturedContentControllerTest.scala
=> #62: Auth0 doesn't allow dashes in role names

src/main/scala/io/digitallibrary/bookapi/service/FeedService.scala, src/test/scala/io/digitallibrary/bookapi/service/FeedServiceTest.scala
GlobalDigitalLibraryio/issues#290
=> #290: Sort on categories

src/main/scala/io/digitallibrary/bookapi/repository/TranslationRepository.scala, src/main/scala/io/digitallibrary/bookapi/service/FeedService.scala, src/main/scala/io/digitallibrary/bookapi/service/ReadService.scala, src/test/scala/io/digitallibrary/bookapi/repository/TranslationRepositoryTest.scala, src/test/scala/io/digitallibrary/bookapi/service/FeedServiceTest.scala
GlobalDigitalLibraryio/issues#289
=> #289: Use category as filter for reading levels if present

src/main/scala/io/digitallibrary/bookapi/controller/OPDSController.scala, src/test/scala/io/digitallibrary/bookapi/TestData.scala, src/test/scala/io/digitallibrary/bookapi/controller/OPDSControllerTest.scala
GlobalDigitalLibraryio/issues#297
=> #297: Use <contributor> when != author

src/main/scala/io/digitallibrary/bookapi/BookApiProperties.scala, src/test/scala/io/digitallibrary/bookapi/TestData.scala, src/test/scala/io/digitallibrary/bookapi/controller/OPDSControllerTest.scala, src/test/scala/io/digitallibrary/bookapi/service/FeedServiceTest.scala
GlobalDigitalLibraryio/issues#278
=> #278: Initial versioning of OPDS endpoints

src/test/scala/io/digitallibrary/bookapi/service/FeedServiceTest.scala
GlobalDigitalLibraryio/issues#278
=> #278: Fix broken test after versioning OPDS endpoints

src/main/scala/io/digitallibrary/bookapi/controller/BooksController.scala, src/main/scala/io/digitallibrary/bookapi/service/ReadService.scala, src/main/scala/io/digitallibrary/bookapi/service/WriteService.scala, src/test/scala/io/digitallibrary/bookapi/TestData.scala, src/test/scala/io/digitallibrary/bookapi/controller/BooksControllerTest.scala
GlobalDigitalLibraryio/issues#303
=> Issue#303 put on endpoints

src/main/scala/io/digitallibrary/bookapi/BookApiProperties.scala, src/main/scala/io/digitallibrary/bookapi/integration/ImageApiClient.scala, src/main/scala/io/digitallibrary/bookapi/model/api/Book.scala, src/main/scala/io/digitallibrary/bookapi/service/ContentConverter.scala, src/main/scala/io/digitallibrary/bookapi/service/ConverterService.scala, src/test/scala/io/digitallibrary/bookapi/TestData.scala, src/test/scala/io/digitallibrary/bookapi/service/ContentConverterTest.scala, src/test/scala/io/digitallibrary/bookapi/service/EPubServiceTest.scala
=> Issue#62 use alttexts from image api when they exist

src/main/scala/io/digitallibrary/bookapi/service/FeedService.scala, src/test/scala/io/digitallibrary/bookapi/service/FeedServiceTest.scala
GlobalDigitalLibraryio/issues#321
=> #321: Correct ordering of selections (levels)

src/main/scala/io/digitallibrary/bookapi/controller/BooksController.scala, src/main/scala/io/digitallibrary/bookapi/service/translation/MergeService.scala, src/test/scala/io/digitallibrary/bookapi/controller/BooksControllerTest.scala
GlobalDigitalLibraryio/issues#323
=> #323: Content conversion on PUT chapter contents

src/main/scala/io/digitallibrary/bookapi/service/PdfService.scala
GlobalDigitalLibraryio/issues#293
=> #293: Added Tigrinya Ethiopic in font-mapping

src/main/scala/io/digitallibrary/bookapi/controller/OPDSController.scala, src/main/scala/io/digitallibrary/bookapi/model/api/Book.scala, src/main/scala/io/digitallibrary/bookapi/service/ConverterService.scala, src/main/scala/io/digitallibrary/bookapi/service/search/IndexService.scala, src/test/scala/io/digitallibrary/bookapi/TestData.scala, src/test/scala/io/digitallibrary/bookapi/controller/BooksControllerTest.scala
=> #62: coverPhoto is replaced by coverImage

src/main/scala/io/digitallibrary/bookapi/service/FeedService.scala
GlobalDigitalLibraryio/issues#329
=> #329: Empty book list in OPDS when feed present but no books in lang

src/main/scala/io/digitallibrary/bookapi/service/search/SearchService.scala
GlobalDigitalLibraryio/issues#330
=> #330: SimpleStringQueryDefinition to avoid errors on special chars

src/main/scala/io/digitallibrary/bookapi/service/ContentConverter.scala, src/test/scala/io/digitallibrary/bookapi/service/ContentConverterTest.scala
GlobalDigitalLibraryio/issues#333
=> #333: Removing 2x image due to unknown image-size

src/main/resources/db/migration/V27__Add_constraints_to_external_id.sql
=> #62: Don't add check constraint

src/main/scala/io/digitallibrary/bookapi/service/search/IndexBuilderService.scala, src/main/scala/io/digitallibrary/bookapi/service/search/IndexService.scala, src/test/scala/io/digitallibrary/bookapi/service/search/IndexBuilderServiceTest.scala
GlobalDigitalLibraryio/issues#338
* Delete old indexes
=> #338 Delete old indexes

src/main/resources/db/migration/V27__Add_category_to_featured_content.sql, src/main/scala/io/digitallibrary/bookapi/controller/FeaturedContentController.scala, src/main/scala/io/digitallibrary/bookapi/controller/NewFeaturedContent.scala, src/main/scala/io/digitallibrary/bookapi/model/api/Book.scala, src/main/scala/io/digitallibrary/bookapi/model/domain/FeaturedContent.scala, src/main/scala/io/digitallibrary/bookapi/repository/CategoryRepository.scala, src/main/scala/io/digitallibrary/bookapi/repository/FeaturedContentRepository.scala, src/main/scala/io/digitallibrary/bookapi/service/ConverterService.scala, src/main/scala/io/digitallibrary/bookapi/service/ReadService.scala, src/main/scala/io/digitallibrary/bookapi/service/WriteService.scala, src/test/scala/io/digitallibrary/bookapi/controller/FeaturedContentControllerTest.scala, src/test/scala/io/digitallibrary/bookapi/repository/FeaturedContentRepositoryTest.scala, src/test/scala/io/digitallibrary/bookapi/service/ValidationServiceTest.scala
GlobalDigitalLibraryio/issues#335 (feil branchnavn)
=> Issue#62 support featured book per category

src/main/resources/db/migration/V28__add_page_orientation_to_translation.sql, src/main/scala/io/digitallibrary/bookapi/controller/BooksController.scala, src/main/scala/io/digitallibrary/bookapi/model/api/Book.scala, src/main/scala/io/digitallibrary/bookapi/model/api/internal/Import.scala, src/main/scala/io/digitallibrary/bookapi/model/api/internal/Internal.scala, src/main/scala/io/digitallibrary/bookapi/model/domain/PdfCss.scala, src/main/scala/io/digitallibrary/bookapi/model/domain/Translation.scala, src/main/scala/io/digitallibrary/bookapi/repository/TranslationRepository.scala, src/main/scala/io/digitallibrary/bookapi/service/ConverterService.scala, src/main/scala/io/digitallibrary/bookapi/service/PdfService.scala, src/test/scala/io/digitallibrary/bookapi/TestData.scala, src/test/scala/io/digitallibrary/bookapi/controller/BooksControllerTest.scala, src/test/scala/io/digitallibrary/bookapi/repository/RepositoryTestHelpers.scala
GlobalDigitalLibraryio/issues#347
=> #347: Added support for landscape and portrait with better css for pdf

build.sbt, src/main/scala/ScalatraBootstrap.scala, src/main/scala/io/digitallibrary/bookapi/BookApiProperties.scala, src/main/scala/io/digitallibrary/bookapi/ComponentRegistry.scala, src/main/scala/io/digitallibrary/bookapi/controller/ExportController.scala, src/main/scala/io/digitallibrary/bookapi/service/ExportService.scala, src/main/scala/io/digitallibrary/bookapi/service/ImportService.scala, src/test/scala/io/digitallibrary/bookapi/TestData.scala, src/test/scala/io/digitallibrary/bookapi/TestEnvironment.scala, src/test/scala/io/digitallibrary/bookapi/controller/BooksControllerTest.scala, src/test/scala/io/digitallibrary/bookapi/controller/ExportControllerTest.scala, src/test/scala/io/digitallibrary/bookapi/controller/FeaturedContentControllerTest.scala, src/test/scala/io/digitallibrary/bookapi/service/ExportServiceTest.scala
Fixes GlobalDigitalLibraryio/issues#344
* Eksport av bøker til csv uten bruk av scripts.
=> #344 Export books from api. Clean up tests.

src/main/scala/io/digitallibrary/bookapi/controller/ExportController.scala
=> #344 Add environment to filename

src/main/scala/io/digitallibrary/bookapi/service/ImportService.scala
GlobalDigitalLibraryio/issues#349
=> #349: Added indexing as last task of import

src/main/scala/io/digitallibrary/bookapi/controller/FeaturedContentController.scala
GlobalDigitalLibraryio/issues#374
=> #374: FeaturedContent is returned, not Book

src/main/scala/io/digitallibrary/bookapi/controller/BooksController.scala, src/main/scala/io/digitallibrary/bookapi/service/ReadService.scala
GlobalDigitalLibraryio/issues#351
=> #351: Add Swagger doc for flagged books

src/main/scala/io/digitallibrary/bookapi/controller/BooksController.scala, src/main/scala/io/digitallibrary/bookapi/model/domain/MyBooksSort.scala, src/main/scala/io/digitallibrary/bookapi/repository/TranslationRepository.scala, src/main/scala/io/digitallibrary/bookapi/service/ReadService.scala
GlobalDigitalLibraryio/issues#392
=> Issue#392 fix sorting of search results

src/main/scala/io/digitallibrary/bookapi/repository/ChapterRepository.scala, src/main/scala/io/digitallibrary/bookapi/service/ImportService.scala, src/test/scala/io/digitallibrary/bookapi/repository/ChapterRepositoryTest.scala, src/test/scala/io/digitallibrary/bookapi/service/ImportServiceTest.scala
GlobalDigitalLibraryio/issues#389
=> #389: Delete redundant chapters on update book

build.sbt
GlobalDigitalLibraryio/issues#395
=> #395: Upgraded dependency to network-library

src/main/scala/io/digitallibrary/bookapi/controller/BooksController.scala, src/main/scala/io/digitallibrary/bookapi/service/ReadService.scala, src/test/scala/io/digitallibrary/bookapi/controller/BooksControllerTest.scala
GlobalDigitalLibraryio/issues#351
=> #351: Return (also flagged) book details if write role in claims

src/main/scala/io/digitallibrary/bookapi/controller/BooksController.scala, src/main/scala/io/digitallibrary/bookapi/service/ReadService.scala, src/main/scala/io/digitallibrary/bookapi/service/WriteService.scala, src/test/scala/io/digitallibrary/bookapi/controller/BooksControllerTest.scala
GlobalDigitalLibraryio/issues#351
=> #351: Allow edit of flagged books if admin

src/main/scala/io/digitallibrary/bookapi/controller/FeaturedContentController.scala, src/test/scala/io/digitallibrary/bookapi/controller/FeaturedContentControllerTest.scala
GlobalDigitalLibraryio/issues#295
=> #295: Set correct content type for delete response

src/main/scala/io/digitallibrary/bookapi/BookApiProperties.scala, src/main/scala/io/digitallibrary/bookapi/controller/SearchController.scala, src/main/scala/io/digitallibrary/bookapi/model/api/Book.scala, src/main/scala/io/digitallibrary/bookapi/service/ReadService.scala, src/main/scala/io/digitallibrary/bookapi/service/search/SearchService.scala, src/test/scala/io/digitallibrary/bookapi/controller/BooksControllerTest.scala, src/test/scala/io/digitallibrary/bookapi/controller/SearchControllerTest.scala, src/test/scala/io/digitallibrary/bookapi/service/ExportServiceTest.scala
GlobalDigitalLibraryio/issues#406
=> #406: Search all book-indexes when no lang is provided

src/main/scala/io/digitallibrary/bookapi/service/EPubService.scala
GlobalDigitalLibraryio/issues#445
=> #445: Need to include coverphoto in order to map correctly in chapters

src/main/scala/io/digitallibrary/bookapi/service/ContentConverter.scala, src/main/scala/io/digitallibrary/bookapi/service/ConverterService.scala, src/main/scala/io/digitallibrary/bookapi/service/PdfService.scala, src/main/scala/io/digitallibrary/bookapi/service/WriteService.scala
GlobalDigitalLibraryio/issues#459
=> #459: Sets size on image if defined from import

src/main/resources/db/migration/V31__add_additional_info.sql, src/main/scala/io/digitallibrary/bookapi/controller/BooksController.scala, src/main/scala/io/digitallibrary/bookapi/model/api/Book.scala, src/main/scala/io/digitallibrary/bookapi/model/api/internal/Import.scala, src/main/scala/io/digitallibrary/bookapi/model/api/internal/Internal.scala, src/main/scala/io/digitallibrary/bookapi/model/domain/Translation.scala, src/main/scala/io/digitallibrary/bookapi/repository/TranslationRepository.scala, src/main/scala/io/digitallibrary/bookapi/service/ConverterService.scala, src/main/scala/io/digitallibrary/bookapi/service/WriteService.scala, src/test/scala/io/digitallibrary/bookapi/TestData.scala, src/test/scala/io/digitallibrary/bookapi/repository/RepositoryTestHelpers.scala
GlobalDigitalLibraryio/issues#461
=> #461: Added extra field for additional information about a book

src/main/scala/io/digitallibrary/bookapi/service/ExportService.scala, src/test/scala/io/digitallibrary/bookapi/service/ExportServiceTest.scala
GlobalDigitalLibraryio/issues#466
=> #466: Retter feil med språk

build.sbt, src/main/scala/io/digitallibrary/bookapi/model/api/Book.scala, src/main/scala/io/digitallibrary/bookapi/service/ConverterService.scala, src/main/scala/io/digitallibrary/bookapi/service/translation/SupportedLanguageService.scala
GlobalDigitalLibraryio/issues#480
=> #480: Added support for showing if a language is RTL

src/main/scala/io/digitallibrary/bookapi/controller/BooksController.scala, src/main/scala/io/digitallibrary/bookapi/model/api/Book.scala, src/main/scala/io/digitallibrary/bookapi/model/domain/ApiContent.scala, src/main/scala/io/digitallibrary/bookapi/service/ContentConverter.scala, src/main/scala/io/digitallibrary/bookapi/service/ConverterService.scala, src/test/scala/io/digitallibrary/bookapi/TestData.scala, src/test/scala/io/digitallibrary/bookapi/controller/BooksControllerTest.scala, src/test/scala/io/digitallibrary/bookapi/service/ContentConverterTest.scala
GlobalDigitalLibraryio/issues#473
=> #473: Changed to include list of all images referenced in chapter

src/main/scala/io/digitallibrary/bookapi/service/ExportService.scala
GlobalDigitalLibraryio/issues#466
=> #466: Changed publisher in export to google play

src/main/scala/io/digitallibrary/bookapi/integration/crowdin/CrowdinClient.scala
GlobalDigitalLibraryio/issues#481
=> #481: Doubled timeout for chapters, and set custom for metadata

src/main/scala/io/digitallibrary/bookapi/integration/ImageApiClient.scala, src/main/scala/io/digitallibrary/bookapi/service/ConverterService.scala
GlobalDigitalLibraryio/issues#471
=> #471: Renamed variables in integration

src/main/scala/io/digitallibrary/bookapi/controller/BooksController.scala, src/main/scala/io/digitallibrary/bookapi/service/ConverterService.scala, src/main/scala/io/digitallibrary/bookapi/service/ReadService.scala, src/main/scala/io/digitallibrary/bookapi/service/WriteService.scala, src/main/scala/io/digitallibrary/bookapi/service/search/IndexService.scala, src/main/scala/io/digitallibrary/bookapi/service/translation/TranslationService.scala, src/test/scala/io/digitallibrary/bookapi/controller/BooksControllerTest.scala
GlobalDigitalLibraryio/issues#482
=> #482: Book is indexed when updated

src/main/scala/io/digitallibrary/bookapi/controller/TranslationsController.scala
GlobalDigitalLibraryio/issues#485
=> #485: Respond with No Content when error occurs from Crowdin

src/main/scala/io/digitallibrary/bookapi/integration/crowdin/CrowdinClient.scala
GlobalDigitalLibraryio/issues#481
=> #481: Increased timeout for all crowdin calls

src/main/scala/io/digitallibrary/bookapi/integration/crowdin/CrowdinClient.scala
GlobalDigitalLibraryio/issues#458
=> #458: Filtering away languages not possible to translate to

src/main/scala/io/digitallibrary/bookapi/model/api/Book.scala, src/main/scala/io/digitallibrary/bookapi/service/ConverterService.scala
fixes https://github.com/GlobalDigitalLibraryio/issues/issues/539
=> #539: added readingLevel to /mine

LICENSE, src/main/resources/log-license.txt, src/main/scala/io/digitallibrary/bookapi/BookApiProperties.scala, src/main/scala/io/digitallibrary/bookapi/BookSwagger.scala
GlobalDigitalLibraryio/issues#580
=> #580: Changed to Apache License 2

src/main/scala/io/digitallibrary/bookapi/service/WriteService.scala
GlobalDigitalLibraryio/issues#598
=> #598: Support for updating source and publisher

src/main/scala/io/digitallibrary/bookapi/controller/LanguageController.scala, src/main/scala/io/digitallibrary/bookapi/service/ExportService.scala, src/test/scala/io/digitallibrary/bookapi/controller/LanguageControllerTest.scala
Endepunkt i language-controller er for å kunne benytte dette i game-service på sikt.
=> Added fields to export. Added language endpoint

src/main/scala/io/digitallibrary/bookapi/controller/ExportController.scala, src/main/scala/io/digitallibrary/bookapi/model/api/Book.scala, src/main/scala/io/digitallibrary/bookapi/service/ConverterService.scala, src/main/scala/io/digitallibrary/bookapi/service/ExportService.scala, src/main/scala/io/digitallibrary/bookapi/service/search/IndexService.scala, src/test/scala/io/digitallibrary/bookapi/TestData.scala, src/test/scala/io/digitallibrary/bookapi/service/ExportServiceTest.scala
Eksport inneholder nå license, og det er mulig å eksportere med "all" som language tag
=> Added license field to BookHit

src/main/scala/io/digitallibrary/bookapi/controller/ExportController.scala, src/main/scala/io/digitallibrary/bookapi/controller/SourceController.scala, src/main/scala/io/digitallibrary/bookapi/repository/SourceRepository.scala
Fikser bug hvor `all` ikke henter alle sources, og en bug hvor antall bøker i source tar med flagged og unlisted.
=> Issue#658 book export

build.sbt, src/main/scala/io/digitallibrary/bookapi/BookApiProperties.scala, src/main/scala/io/digitallibrary/bookapi/controller/BooksController.scala, src/main/scala/io/digitallibrary/bookapi/integration/ImageApiClient.scala, src/main/scala/io/digitallibrary/bookapi/service/translation/MergeService.scala, src/test/scala/io/digitallibrary/bookapi/UnitSuite.scala, src/test/scala/io/digitallibrary/bookapi/controller/BooksControllerTest.scala
Da skal det fungere å endre/legge til nye bilder. Det tar nå litt lengere tid siden den må innom image-apiet for hvert bilde. Hvis ikke bildet eksisterer i image-apiet så vil den prøve å laste ned og oprette nytt bilde.
ExternalId er beregnet slik det blir gjort i import-scriptet.
Jeg er ikke så godt kjent med Scala så her er det bare å slakte i vei ;)
=> Edit images in admin-page
